debezium.sink.type=kafka
debezium.sink.kafka.bootstrap.servers=cdc-kafka:9092

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=cdc-postgres
debezium.source.database.port=5432
debezium.source.database.user=postgres
debezium.source.database.password=postgres
debezium.source.database.dbname=cdc_db
debezium.source.database.server.name=cdc-server
debezium.source.table.include.list=public.*
debezium.source.topic.prefix=cdc

key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer
debezium.transforms=unwrap
debezium.transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState