version: "3.9"

vars:

  DEBEZIUM_PORT: "{{.DEBEZIUM_PORT}}"
  CONNECTOR_SRC: src_connector

tasks:
  up:
    desc: Start all services
    cmds:
      - docker compose up -d
    status:
      - docker compose ps | grep -q "Up"

  down:
    desc: Stop all services
    cmds:
      - docker compose down -v

  default:
    desc: Restart all services
    cmds:
      - task: down
      - task: up
      - task: configure

  configure:
    desc: Configure Debezium connector
    cmds:
      - |
        sleep 15 && \
        curl -X POST http://localhost:{{.DEBEZIUM_PORT}}/connectors \
        -H "Content-Type: application/json" \
        -d @./debezium-config/{{.CONNECTOR_SRC}}.json && \
        sleep 1 && \
        curl -X GET http://localhost:{{.DEBEZIUM_PORT}}/connectors/{{.CONNECTOR_SRC}}/status | jq